name: diploma

services:
  postgres:
    image: postgres:latest
    container_name: drone-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: drone
      POSTGRES_PASSWORD: drone123
      POSTGRES_DB: dronedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosqdata:/mosquitto/data
    ports:
      - "1883:1883"
      - "9001:9001"

  api:
    build:
      context: .           # тепер у контексті весь репозиторій
      dockerfile: Dockerfile
    depends_on: [postgres, mosquitto]
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=dronedb;Username=drone;Password=drone123"
    ports:
      - "5000:8080"

  yolov5-api:
    image: ultralytics/yolov5:latest
    container_name: yolov5-api
    command: >
      python detect.py --source rtsp://camera_stream --weights yolov5s.pt
    ports:
      - "5001:5000"    

volumes:
  pgdata:   {}
  mosqdata: {}