name: diploma

services:
  postgres:
    image: postgres:latest
    container_name: drone-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: drone
      POSTGRES_PASSWORD: drone123
      POSTGRES_DB: dronedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosqdata:/mosquitto/data
    ports:
      - "1883:1883"
      - "9001:9001"

  api:
    build:
      context: .           # тепер у контексті весь репозиторій
      dockerfile: Dockerfile
    depends_on: [postgres, mosquitto]
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=dronedb;Username=drone;Password=drone123"
    ports:
      - "8080:8080"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8081:80"   # dashboard буде на localhost:8081

volumes:
  pgdata:   {}
  mosqdata: {}